name: SopDataCacher
main: net.enelson.sopdatacacher.SopDataCacher
version: ${project.version}
authors: [E_NeLsOn]
depend: [PlaceholderAPI]
api-version: 1.16
commands:
  sopdatacacher:
permissions:
  sopdatacacher.admin:
    default: op
  adatacacher.admin:
    default: op
